# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /stock/sunseille/programmation/C++/panel-pop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /stock/sunseille/programmation/C++/panel-pop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /stock/sunseille/programmation/C++/panel-pop/CMakeFiles /stock/sunseille/programmation/C++/panel-pop/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /stock/sunseille/programmation/C++/panel-pop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named panel-pop

# Build rule for target.
panel-pop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 panel-pop
.PHONY : panel-pop

# fast build rule for target.
panel-pop/fast:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/build
.PHONY : panel-pop/fast

AI/AIBoardController.o: AI/AIBoardController.cpp.o

.PHONY : AI/AIBoardController.o

# target to build an object file
AI/AIBoardController.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/AI/AIBoardController.cpp.o
.PHONY : AI/AIBoardController.cpp.o

AI/AIBoardController.i: AI/AIBoardController.cpp.i

.PHONY : AI/AIBoardController.i

# target to preprocess a source file
AI/AIBoardController.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/AI/AIBoardController.cpp.i
.PHONY : AI/AIBoardController.cpp.i

AI/AIBoardController.s: AI/AIBoardController.cpp.s

.PHONY : AI/AIBoardController.s

# target to generate assembly for a file
AI/AIBoardController.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/AI/AIBoardController.cpp.s
.PHONY : AI/AIBoardController.cpp.s

AI/BoardScanner.o: AI/BoardScanner.cpp.o

.PHONY : AI/BoardScanner.o

# target to build an object file
AI/BoardScanner.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/AI/BoardScanner.cpp.o
.PHONY : AI/BoardScanner.cpp.o

AI/BoardScanner.i: AI/BoardScanner.cpp.i

.PHONY : AI/BoardScanner.i

# target to preprocess a source file
AI/BoardScanner.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/AI/BoardScanner.cpp.i
.PHONY : AI/BoardScanner.cpp.i

AI/BoardScanner.s: AI/BoardScanner.cpp.s

.PHONY : AI/BoardScanner.s

# target to generate assembly for a file
AI/BoardScanner.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/AI/BoardScanner.cpp.s
.PHONY : AI/BoardScanner.cpp.s

Config/ConfigHandler.o: Config/ConfigHandler.cpp.o

.PHONY : Config/ConfigHandler.o

# target to build an object file
Config/ConfigHandler.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Config/ConfigHandler.cpp.o
.PHONY : Config/ConfigHandler.cpp.o

Config/ConfigHandler.i: Config/ConfigHandler.cpp.i

.PHONY : Config/ConfigHandler.i

# target to preprocess a source file
Config/ConfigHandler.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Config/ConfigHandler.cpp.i
.PHONY : Config/ConfigHandler.cpp.i

Config/ConfigHandler.s: Config/ConfigHandler.cpp.s

.PHONY : Config/ConfigHandler.s

# target to generate assembly for a file
Config/ConfigHandler.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Config/ConfigHandler.cpp.s
.PHONY : Config/ConfigHandler.cpp.s

Game/Block.o: Game/Block.cpp.o

.PHONY : Game/Block.o

# target to build an object file
Game/Block.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Block.cpp.o
.PHONY : Game/Block.cpp.o

Game/Block.i: Game/Block.cpp.i

.PHONY : Game/Block.i

# target to preprocess a source file
Game/Block.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Block.cpp.i
.PHONY : Game/Block.cpp.i

Game/Block.s: Game/Block.cpp.s

.PHONY : Game/Block.s

# target to generate assembly for a file
Game/Block.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Block.cpp.s
.PHONY : Game/Block.cpp.s

Game/Board.o: Game/Board.cpp.o

.PHONY : Game/Board.o

# target to build an object file
Game/Board.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Board.cpp.o
.PHONY : Game/Board.cpp.o

Game/Board.i: Game/Board.cpp.i

.PHONY : Game/Board.i

# target to preprocess a source file
Game/Board.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Board.cpp.i
.PHONY : Game/Board.cpp.i

Game/Board.s: Game/Board.cpp.s

.PHONY : Game/Board.s

# target to generate assembly for a file
Game/Board.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Board.cpp.s
.PHONY : Game/Board.cpp.s

Game/BoardController.o: Game/BoardController.cpp.o

.PHONY : Game/BoardController.o

# target to build an object file
Game/BoardController.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/BoardController.cpp.o
.PHONY : Game/BoardController.cpp.o

Game/BoardController.i: Game/BoardController.cpp.i

.PHONY : Game/BoardController.i

# target to preprocess a source file
Game/BoardController.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/BoardController.cpp.i
.PHONY : Game/BoardController.cpp.i

Game/BoardController.s: Game/BoardController.cpp.s

.PHONY : Game/BoardController.s

# target to generate assembly for a file
Game/BoardController.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/BoardController.cpp.s
.PHONY : Game/BoardController.cpp.s

Game/BoardEventHandler.o: Game/BoardEventHandler.cpp.o

.PHONY : Game/BoardEventHandler.o

# target to build an object file
Game/BoardEventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/BoardEventHandler.cpp.o
.PHONY : Game/BoardEventHandler.cpp.o

Game/BoardEventHandler.i: Game/BoardEventHandler.cpp.i

.PHONY : Game/BoardEventHandler.i

# target to preprocess a source file
Game/BoardEventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/BoardEventHandler.cpp.i
.PHONY : Game/BoardEventHandler.cpp.i

Game/BoardEventHandler.s: Game/BoardEventHandler.cpp.s

.PHONY : Game/BoardEventHandler.s

# target to generate assembly for a file
Game/BoardEventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/BoardEventHandler.cpp.s
.PHONY : Game/BoardEventHandler.cpp.s

Game/EndlessGame.o: Game/EndlessGame.cpp.o

.PHONY : Game/EndlessGame.o

# target to build an object file
Game/EndlessGame.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/EndlessGame.cpp.o
.PHONY : Game/EndlessGame.cpp.o

Game/EndlessGame.i: Game/EndlessGame.cpp.i

.PHONY : Game/EndlessGame.i

# target to preprocess a source file
Game/EndlessGame.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/EndlessGame.cpp.i
.PHONY : Game/EndlessGame.cpp.i

Game/EndlessGame.s: Game/EndlessGame.cpp.s

.PHONY : Game/EndlessGame.s

# target to generate assembly for a file
Game/EndlessGame.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/EndlessGame.cpp.s
.PHONY : Game/EndlessGame.cpp.s

Game/Game.o: Game/Game.cpp.o

.PHONY : Game/Game.o

# target to build an object file
Game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Game.cpp.o
.PHONY : Game/Game.cpp.o

Game/Game.i: Game/Game.cpp.i

.PHONY : Game/Game.i

# target to preprocess a source file
Game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Game.cpp.i
.PHONY : Game/Game.cpp.i

Game/Game.s: Game/Game.cpp.s

.PHONY : Game/Game.s

# target to generate assembly for a file
Game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/Game.cpp.s
.PHONY : Game/Game.cpp.s

Game/GameEventHandler.o: Game/GameEventHandler.cpp.o

.PHONY : Game/GameEventHandler.o

# target to build an object file
Game/GameEventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/GameEventHandler.cpp.o
.PHONY : Game/GameEventHandler.cpp.o

Game/GameEventHandler.i: Game/GameEventHandler.cpp.i

.PHONY : Game/GameEventHandler.i

# target to preprocess a source file
Game/GameEventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/GameEventHandler.cpp.i
.PHONY : Game/GameEventHandler.cpp.i

Game/GameEventHandler.s: Game/GameEventHandler.cpp.s

.PHONY : Game/GameEventHandler.s

# target to generate assembly for a file
Game/GameEventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/GameEventHandler.cpp.s
.PHONY : Game/GameEventHandler.cpp.s

Game/GarbageBlock.o: Game/GarbageBlock.cpp.o

.PHONY : Game/GarbageBlock.o

# target to build an object file
Game/GarbageBlock.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/GarbageBlock.cpp.o
.PHONY : Game/GarbageBlock.cpp.o

Game/GarbageBlock.i: Game/GarbageBlock.cpp.i

.PHONY : Game/GarbageBlock.i

# target to preprocess a source file
Game/GarbageBlock.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/GarbageBlock.cpp.i
.PHONY : Game/GarbageBlock.cpp.i

Game/GarbageBlock.s: Game/GarbageBlock.cpp.s

.PHONY : Game/GarbageBlock.s

# target to generate assembly for a file
Game/GarbageBlock.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/GarbageBlock.cpp.s
.PHONY : Game/GarbageBlock.cpp.s

Game/KeyboardController.o: Game/KeyboardController.cpp.o

.PHONY : Game/KeyboardController.o

# target to build an object file
Game/KeyboardController.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/KeyboardController.cpp.o
.PHONY : Game/KeyboardController.cpp.o

Game/KeyboardController.i: Game/KeyboardController.cpp.i

.PHONY : Game/KeyboardController.i

# target to preprocess a source file
Game/KeyboardController.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/KeyboardController.cpp.i
.PHONY : Game/KeyboardController.cpp.i

Game/KeyboardController.s: Game/KeyboardController.cpp.s

.PHONY : Game/KeyboardController.s

# target to generate assembly for a file
Game/KeyboardController.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/KeyboardController.cpp.s
.PHONY : Game/KeyboardController.cpp.s

Game/VsGame.o: Game/VsGame.cpp.o

.PHONY : Game/VsGame.o

# target to build an object file
Game/VsGame.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/VsGame.cpp.o
.PHONY : Game/VsGame.cpp.o

Game/VsGame.i: Game/VsGame.cpp.i

.PHONY : Game/VsGame.i

# target to preprocess a source file
Game/VsGame.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/VsGame.cpp.i
.PHONY : Game/VsGame.cpp.i

Game/VsGame.s: Game/VsGame.cpp.s

.PHONY : Game/VsGame.s

# target to generate assembly for a file
Game/VsGame.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Game/VsGame.cpp.s
.PHONY : Game/VsGame.cpp.s

InputManager.o: InputManager.cpp.o

.PHONY : InputManager.o

# target to build an object file
InputManager.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/InputManager.cpp.o
.PHONY : InputManager.cpp.o

InputManager.i: InputManager.cpp.i

.PHONY : InputManager.i

# target to preprocess a source file
InputManager.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/InputManager.cpp.i
.PHONY : InputManager.cpp.i

InputManager.s: InputManager.cpp.s

.PHONY : InputManager.s

# target to generate assembly for a file
InputManager.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/InputManager.cpp.s
.PHONY : InputManager.cpp.s

Menus/KeyConfigMenu.o: Menus/KeyConfigMenu.cpp.o

.PHONY : Menus/KeyConfigMenu.o

# target to build an object file
Menus/KeyConfigMenu.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/KeyConfigMenu.cpp.o
.PHONY : Menus/KeyConfigMenu.cpp.o

Menus/KeyConfigMenu.i: Menus/KeyConfigMenu.cpp.i

.PHONY : Menus/KeyConfigMenu.i

# target to preprocess a source file
Menus/KeyConfigMenu.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/KeyConfigMenu.cpp.i
.PHONY : Menus/KeyConfigMenu.cpp.i

Menus/KeyConfigMenu.s: Menus/KeyConfigMenu.cpp.s

.PHONY : Menus/KeyConfigMenu.s

# target to generate assembly for a file
Menus/KeyConfigMenu.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/KeyConfigMenu.cpp.s
.PHONY : Menus/KeyConfigMenu.cpp.s

Menus/MainMenu.o: Menus/MainMenu.cpp.o

.PHONY : Menus/MainMenu.o

# target to build an object file
Menus/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/MainMenu.cpp.o
.PHONY : Menus/MainMenu.cpp.o

Menus/MainMenu.i: Menus/MainMenu.cpp.i

.PHONY : Menus/MainMenu.i

# target to preprocess a source file
Menus/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/MainMenu.cpp.i
.PHONY : Menus/MainMenu.cpp.i

Menus/MainMenu.s: Menus/MainMenu.cpp.s

.PHONY : Menus/MainMenu.s

# target to generate assembly for a file
Menus/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/MainMenu.cpp.s
.PHONY : Menus/MainMenu.cpp.s

Menus/Menu.o: Menus/Menu.cpp.o

.PHONY : Menus/Menu.o

# target to build an object file
Menus/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/Menu.cpp.o
.PHONY : Menus/Menu.cpp.o

Menus/Menu.i: Menus/Menu.cpp.i

.PHONY : Menus/Menu.i

# target to preprocess a source file
Menus/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/Menu.cpp.i
.PHONY : Menus/Menu.cpp.i

Menus/Menu.s: Menus/Menu.cpp.s

.PHONY : Menus/Menu.s

# target to generate assembly for a file
Menus/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/Menu.cpp.s
.PHONY : Menus/Menu.cpp.s

Menus/MenuItem.o: Menus/MenuItem.cpp.o

.PHONY : Menus/MenuItem.o

# target to build an object file
Menus/MenuItem.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/MenuItem.cpp.o
.PHONY : Menus/MenuItem.cpp.o

Menus/MenuItem.i: Menus/MenuItem.cpp.i

.PHONY : Menus/MenuItem.i

# target to preprocess a source file
Menus/MenuItem.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/MenuItem.cpp.i
.PHONY : Menus/MenuItem.cpp.i

Menus/MenuItem.s: Menus/MenuItem.cpp.s

.PHONY : Menus/MenuItem.s

# target to generate assembly for a file
Menus/MenuItem.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/MenuItem.cpp.s
.PHONY : Menus/MenuItem.cpp.s

Menus/OptionsMenu.o: Menus/OptionsMenu.cpp.o

.PHONY : Menus/OptionsMenu.o

# target to build an object file
Menus/OptionsMenu.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/OptionsMenu.cpp.o
.PHONY : Menus/OptionsMenu.cpp.o

Menus/OptionsMenu.i: Menus/OptionsMenu.cpp.i

.PHONY : Menus/OptionsMenu.i

# target to preprocess a source file
Menus/OptionsMenu.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/OptionsMenu.cpp.i
.PHONY : Menus/OptionsMenu.cpp.i

Menus/OptionsMenu.s: Menus/OptionsMenu.cpp.s

.PHONY : Menus/OptionsMenu.s

# target to generate assembly for a file
Menus/OptionsMenu.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/OptionsMenu.cpp.s
.PHONY : Menus/OptionsMenu.cpp.s

Menus/PauseMenu.o: Menus/PauseMenu.cpp.o

.PHONY : Menus/PauseMenu.o

# target to build an object file
Menus/PauseMenu.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/PauseMenu.cpp.o
.PHONY : Menus/PauseMenu.cpp.o

Menus/PauseMenu.i: Menus/PauseMenu.cpp.i

.PHONY : Menus/PauseMenu.i

# target to preprocess a source file
Menus/PauseMenu.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/PauseMenu.cpp.i
.PHONY : Menus/PauseMenu.cpp.i

Menus/PauseMenu.s: Menus/PauseMenu.cpp.s

.PHONY : Menus/PauseMenu.s

# target to generate assembly for a file
Menus/PauseMenu.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Menus/PauseMenu.cpp.s
.PHONY : Menus/PauseMenu.cpp.s

Rendering/BoardRenderer.o: Rendering/BoardRenderer.cpp.o

.PHONY : Rendering/BoardRenderer.o

# target to build an object file
Rendering/BoardRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/BoardRenderer.cpp.o
.PHONY : Rendering/BoardRenderer.cpp.o

Rendering/BoardRenderer.i: Rendering/BoardRenderer.cpp.i

.PHONY : Rendering/BoardRenderer.i

# target to preprocess a source file
Rendering/BoardRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/BoardRenderer.cpp.i
.PHONY : Rendering/BoardRenderer.cpp.i

Rendering/BoardRenderer.s: Rendering/BoardRenderer.cpp.s

.PHONY : Rendering/BoardRenderer.s

# target to generate assembly for a file
Rendering/BoardRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/BoardRenderer.cpp.s
.PHONY : Rendering/BoardRenderer.cpp.s

Rendering/ChainPopup.o: Rendering/ChainPopup.cpp.o

.PHONY : Rendering/ChainPopup.o

# target to build an object file
Rendering/ChainPopup.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/ChainPopup.cpp.o
.PHONY : Rendering/ChainPopup.cpp.o

Rendering/ChainPopup.i: Rendering/ChainPopup.cpp.i

.PHONY : Rendering/ChainPopup.i

# target to preprocess a source file
Rendering/ChainPopup.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/ChainPopup.cpp.i
.PHONY : Rendering/ChainPopup.cpp.i

Rendering/ChainPopup.s: Rendering/ChainPopup.cpp.s

.PHONY : Rendering/ChainPopup.s

# target to generate assembly for a file
Rendering/ChainPopup.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/ChainPopup.cpp.s
.PHONY : Rendering/ChainPopup.cpp.s

Rendering/ComboPopup.o: Rendering/ComboPopup.cpp.o

.PHONY : Rendering/ComboPopup.o

# target to build an object file
Rendering/ComboPopup.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/ComboPopup.cpp.o
.PHONY : Rendering/ComboPopup.cpp.o

Rendering/ComboPopup.i: Rendering/ComboPopup.cpp.i

.PHONY : Rendering/ComboPopup.i

# target to preprocess a source file
Rendering/ComboPopup.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/ComboPopup.cpp.i
.PHONY : Rendering/ComboPopup.cpp.i

Rendering/ComboPopup.s: Rendering/ComboPopup.cpp.s

.PHONY : Rendering/ComboPopup.s

# target to generate assembly for a file
Rendering/ComboPopup.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/ComboPopup.cpp.s
.PHONY : Rendering/ComboPopup.cpp.s

Rendering/EndlessGameRenderer.o: Rendering/EndlessGameRenderer.cpp.o

.PHONY : Rendering/EndlessGameRenderer.o

# target to build an object file
Rendering/EndlessGameRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/EndlessGameRenderer.cpp.o
.PHONY : Rendering/EndlessGameRenderer.cpp.o

Rendering/EndlessGameRenderer.i: Rendering/EndlessGameRenderer.cpp.i

.PHONY : Rendering/EndlessGameRenderer.i

# target to preprocess a source file
Rendering/EndlessGameRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/EndlessGameRenderer.cpp.i
.PHONY : Rendering/EndlessGameRenderer.cpp.i

Rendering/EndlessGameRenderer.s: Rendering/EndlessGameRenderer.cpp.s

.PHONY : Rendering/EndlessGameRenderer.s

# target to generate assembly for a file
Rendering/EndlessGameRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/EndlessGameRenderer.cpp.s
.PHONY : Rendering/EndlessGameRenderer.cpp.s

Rendering/GameRenderer.o: Rendering/GameRenderer.cpp.o

.PHONY : Rendering/GameRenderer.o

# target to build an object file
Rendering/GameRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/GameRenderer.cpp.o
.PHONY : Rendering/GameRenderer.cpp.o

Rendering/GameRenderer.i: Rendering/GameRenderer.cpp.i

.PHONY : Rendering/GameRenderer.i

# target to preprocess a source file
Rendering/GameRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/GameRenderer.cpp.i
.PHONY : Rendering/GameRenderer.cpp.i

Rendering/GameRenderer.s: Rendering/GameRenderer.cpp.s

.PHONY : Rendering/GameRenderer.s

# target to generate assembly for a file
Rendering/GameRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/GameRenderer.cpp.s
.PHONY : Rendering/GameRenderer.cpp.s

Rendering/GbQueueRenderer.o: Rendering/GbQueueRenderer.cpp.o

.PHONY : Rendering/GbQueueRenderer.o

# target to build an object file
Rendering/GbQueueRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/GbQueueRenderer.cpp.o
.PHONY : Rendering/GbQueueRenderer.cpp.o

Rendering/GbQueueRenderer.i: Rendering/GbQueueRenderer.cpp.i

.PHONY : Rendering/GbQueueRenderer.i

# target to preprocess a source file
Rendering/GbQueueRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/GbQueueRenderer.cpp.i
.PHONY : Rendering/GbQueueRenderer.cpp.i

Rendering/GbQueueRenderer.s: Rendering/GbQueueRenderer.cpp.s

.PHONY : Rendering/GbQueueRenderer.s

# target to generate assembly for a file
Rendering/GbQueueRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/GbQueueRenderer.cpp.s
.PHONY : Rendering/GbQueueRenderer.cpp.s

Rendering/Particle.o: Rendering/Particle.cpp.o

.PHONY : Rendering/Particle.o

# target to build an object file
Rendering/Particle.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Particle.cpp.o
.PHONY : Rendering/Particle.cpp.o

Rendering/Particle.i: Rendering/Particle.cpp.i

.PHONY : Rendering/Particle.i

# target to preprocess a source file
Rendering/Particle.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Particle.cpp.i
.PHONY : Rendering/Particle.cpp.i

Rendering/Particle.s: Rendering/Particle.cpp.s

.PHONY : Rendering/Particle.s

# target to generate assembly for a file
Rendering/Particle.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Particle.cpp.s
.PHONY : Rendering/Particle.cpp.s

Rendering/Popup.o: Rendering/Popup.cpp.o

.PHONY : Rendering/Popup.o

# target to build an object file
Rendering/Popup.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Popup.cpp.o
.PHONY : Rendering/Popup.cpp.o

Rendering/Popup.i: Rendering/Popup.cpp.i

.PHONY : Rendering/Popup.i

# target to preprocess a source file
Rendering/Popup.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Popup.cpp.i
.PHONY : Rendering/Popup.cpp.i

Rendering/Popup.s: Rendering/Popup.cpp.s

.PHONY : Rendering/Popup.s

# target to generate assembly for a file
Rendering/Popup.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Popup.cpp.s
.PHONY : Rendering/Popup.cpp.s

Rendering/Renderer.o: Rendering/Renderer.cpp.o

.PHONY : Rendering/Renderer.o

# target to build an object file
Rendering/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Renderer.cpp.o
.PHONY : Rendering/Renderer.cpp.o

Rendering/Renderer.i: Rendering/Renderer.cpp.i

.PHONY : Rendering/Renderer.i

# target to preprocess a source file
Rendering/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Renderer.cpp.i
.PHONY : Rendering/Renderer.cpp.i

Rendering/Renderer.s: Rendering/Renderer.cpp.s

.PHONY : Rendering/Renderer.s

# target to generate assembly for a file
Rendering/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/Renderer.cpp.s
.PHONY : Rendering/Renderer.cpp.s

Rendering/TitleScreenRenderer.o: Rendering/TitleScreenRenderer.cpp.o

.PHONY : Rendering/TitleScreenRenderer.o

# target to build an object file
Rendering/TitleScreenRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/TitleScreenRenderer.cpp.o
.PHONY : Rendering/TitleScreenRenderer.cpp.o

Rendering/TitleScreenRenderer.i: Rendering/TitleScreenRenderer.cpp.i

.PHONY : Rendering/TitleScreenRenderer.i

# target to preprocess a source file
Rendering/TitleScreenRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/TitleScreenRenderer.cpp.i
.PHONY : Rendering/TitleScreenRenderer.cpp.i

Rendering/TitleScreenRenderer.s: Rendering/TitleScreenRenderer.cpp.s

.PHONY : Rendering/TitleScreenRenderer.s

# target to generate assembly for a file
Rendering/TitleScreenRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/TitleScreenRenderer.cpp.s
.PHONY : Rendering/TitleScreenRenderer.cpp.s

Rendering/VsGameRenderer.o: Rendering/VsGameRenderer.cpp.o

.PHONY : Rendering/VsGameRenderer.o

# target to build an object file
Rendering/VsGameRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/VsGameRenderer.cpp.o
.PHONY : Rendering/VsGameRenderer.cpp.o

Rendering/VsGameRenderer.i: Rendering/VsGameRenderer.cpp.i

.PHONY : Rendering/VsGameRenderer.i

# target to preprocess a source file
Rendering/VsGameRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/VsGameRenderer.cpp.i
.PHONY : Rendering/VsGameRenderer.cpp.i

Rendering/VsGameRenderer.s: Rendering/VsGameRenderer.cpp.s

.PHONY : Rendering/VsGameRenderer.s

# target to generate assembly for a file
Rendering/VsGameRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/Rendering/VsGameRenderer.cpp.s
.PHONY : Rendering/VsGameRenderer.cpp.s

SDLContext.o: SDLContext.cpp.o

.PHONY : SDLContext.o

# target to build an object file
SDLContext.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/SDLContext.cpp.o
.PHONY : SDLContext.cpp.o

SDLContext.i: SDLContext.cpp.i

.PHONY : SDLContext.i

# target to preprocess a source file
SDLContext.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/SDLContext.cpp.i
.PHONY : SDLContext.cpp.i

SDLContext.s: SDLContext.cpp.s

.PHONY : SDLContext.s

# target to generate assembly for a file
SDLContext.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/SDLContext.cpp.s
.PHONY : SDLContext.cpp.s

States/AIGameState.o: States/AIGameState.cpp.o

.PHONY : States/AIGameState.o

# target to build an object file
States/AIGameState.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/AIGameState.cpp.o
.PHONY : States/AIGameState.cpp.o

States/AIGameState.i: States/AIGameState.cpp.i

.PHONY : States/AIGameState.i

# target to preprocess a source file
States/AIGameState.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/AIGameState.cpp.i
.PHONY : States/AIGameState.cpp.i

States/AIGameState.s: States/AIGameState.cpp.s

.PHONY : States/AIGameState.s

# target to generate assembly for a file
States/AIGameState.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/AIGameState.cpp.s
.PHONY : States/AIGameState.cpp.s

States/DemoGameState.o: States/DemoGameState.cpp.o

.PHONY : States/DemoGameState.o

# target to build an object file
States/DemoGameState.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/DemoGameState.cpp.o
.PHONY : States/DemoGameState.cpp.o

States/DemoGameState.i: States/DemoGameState.cpp.i

.PHONY : States/DemoGameState.i

# target to preprocess a source file
States/DemoGameState.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/DemoGameState.cpp.i
.PHONY : States/DemoGameState.cpp.i

States/DemoGameState.s: States/DemoGameState.cpp.s

.PHONY : States/DemoGameState.s

# target to generate assembly for a file
States/DemoGameState.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/DemoGameState.cpp.s
.PHONY : States/DemoGameState.cpp.s

States/EndlessGameState.o: States/EndlessGameState.cpp.o

.PHONY : States/EndlessGameState.o

# target to build an object file
States/EndlessGameState.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/EndlessGameState.cpp.o
.PHONY : States/EndlessGameState.cpp.o

States/EndlessGameState.i: States/EndlessGameState.cpp.i

.PHONY : States/EndlessGameState.i

# target to preprocess a source file
States/EndlessGameState.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/EndlessGameState.cpp.i
.PHONY : States/EndlessGameState.cpp.i

States/EndlessGameState.s: States/EndlessGameState.cpp.s

.PHONY : States/EndlessGameState.s

# target to generate assembly for a file
States/EndlessGameState.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/EndlessGameState.cpp.s
.PHONY : States/EndlessGameState.cpp.s

States/FadeTransition.o: States/FadeTransition.cpp.o

.PHONY : States/FadeTransition.o

# target to build an object file
States/FadeTransition.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/FadeTransition.cpp.o
.PHONY : States/FadeTransition.cpp.o

States/FadeTransition.i: States/FadeTransition.cpp.i

.PHONY : States/FadeTransition.i

# target to preprocess a source file
States/FadeTransition.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/FadeTransition.cpp.i
.PHONY : States/FadeTransition.cpp.i

States/FadeTransition.s: States/FadeTransition.cpp.s

.PHONY : States/FadeTransition.s

# target to generate assembly for a file
States/FadeTransition.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/FadeTransition.cpp.s
.PHONY : States/FadeTransition.cpp.s

States/GameState.o: States/GameState.cpp.o

.PHONY : States/GameState.o

# target to build an object file
States/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/GameState.cpp.o
.PHONY : States/GameState.cpp.o

States/GameState.i: States/GameState.cpp.i

.PHONY : States/GameState.i

# target to preprocess a source file
States/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/GameState.cpp.i
.PHONY : States/GameState.cpp.i

States/GameState.s: States/GameState.cpp.s

.PHONY : States/GameState.s

# target to generate assembly for a file
States/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/GameState.cpp.s
.PHONY : States/GameState.cpp.s

States/OptionsMenuState.o: States/OptionsMenuState.cpp.o

.PHONY : States/OptionsMenuState.o

# target to build an object file
States/OptionsMenuState.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/OptionsMenuState.cpp.o
.PHONY : States/OptionsMenuState.cpp.o

States/OptionsMenuState.i: States/OptionsMenuState.cpp.i

.PHONY : States/OptionsMenuState.i

# target to preprocess a source file
States/OptionsMenuState.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/OptionsMenuState.cpp.i
.PHONY : States/OptionsMenuState.cpp.i

States/OptionsMenuState.s: States/OptionsMenuState.cpp.s

.PHONY : States/OptionsMenuState.s

# target to generate assembly for a file
States/OptionsMenuState.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/OptionsMenuState.cpp.s
.PHONY : States/OptionsMenuState.cpp.s

States/State.o: States/State.cpp.o

.PHONY : States/State.o

# target to build an object file
States/State.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/State.cpp.o
.PHONY : States/State.cpp.o

States/State.i: States/State.cpp.i

.PHONY : States/State.i

# target to preprocess a source file
States/State.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/State.cpp.i
.PHONY : States/State.cpp.i

States/State.s: States/State.cpp.s

.PHONY : States/State.s

# target to generate assembly for a file
States/State.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/State.cpp.s
.PHONY : States/State.cpp.s

States/StateManager.o: States/StateManager.cpp.o

.PHONY : States/StateManager.o

# target to build an object file
States/StateManager.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/StateManager.cpp.o
.PHONY : States/StateManager.cpp.o

States/StateManager.i: States/StateManager.cpp.i

.PHONY : States/StateManager.i

# target to preprocess a source file
States/StateManager.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/StateManager.cpp.i
.PHONY : States/StateManager.cpp.i

States/StateManager.s: States/StateManager.cpp.s

.PHONY : States/StateManager.s

# target to generate assembly for a file
States/StateManager.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/StateManager.cpp.s
.PHONY : States/StateManager.cpp.s

States/TitleScreen.o: States/TitleScreen.cpp.o

.PHONY : States/TitleScreen.o

# target to build an object file
States/TitleScreen.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/TitleScreen.cpp.o
.PHONY : States/TitleScreen.cpp.o

States/TitleScreen.i: States/TitleScreen.cpp.i

.PHONY : States/TitleScreen.i

# target to preprocess a source file
States/TitleScreen.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/TitleScreen.cpp.i
.PHONY : States/TitleScreen.cpp.i

States/TitleScreen.s: States/TitleScreen.cpp.s

.PHONY : States/TitleScreen.s

# target to generate assembly for a file
States/TitleScreen.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/TitleScreen.cpp.s
.PHONY : States/TitleScreen.cpp.s

States/VsGameState.o: States/VsGameState.cpp.o

.PHONY : States/VsGameState.o

# target to build an object file
States/VsGameState.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/VsGameState.cpp.o
.PHONY : States/VsGameState.cpp.o

States/VsGameState.i: States/VsGameState.cpp.i

.PHONY : States/VsGameState.i

# target to preprocess a source file
States/VsGameState.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/VsGameState.cpp.i
.PHONY : States/VsGameState.cpp.i

States/VsGameState.s: States/VsGameState.cpp.s

.PHONY : States/VsGameState.s

# target to generate assembly for a file
States/VsGameState.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/States/VsGameState.cpp.s
.PHONY : States/VsGameState.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/panel-pop.dir/build.make CMakeFiles/panel-pop.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... panel-pop"
	@echo "... edit_cache"
	@echo "... AI/AIBoardController.o"
	@echo "... AI/AIBoardController.i"
	@echo "... AI/AIBoardController.s"
	@echo "... AI/BoardScanner.o"
	@echo "... AI/BoardScanner.i"
	@echo "... AI/BoardScanner.s"
	@echo "... Config/ConfigHandler.o"
	@echo "... Config/ConfigHandler.i"
	@echo "... Config/ConfigHandler.s"
	@echo "... Game/Block.o"
	@echo "... Game/Block.i"
	@echo "... Game/Block.s"
	@echo "... Game/Board.o"
	@echo "... Game/Board.i"
	@echo "... Game/Board.s"
	@echo "... Game/BoardController.o"
	@echo "... Game/BoardController.i"
	@echo "... Game/BoardController.s"
	@echo "... Game/BoardEventHandler.o"
	@echo "... Game/BoardEventHandler.i"
	@echo "... Game/BoardEventHandler.s"
	@echo "... Game/EndlessGame.o"
	@echo "... Game/EndlessGame.i"
	@echo "... Game/EndlessGame.s"
	@echo "... Game/Game.o"
	@echo "... Game/Game.i"
	@echo "... Game/Game.s"
	@echo "... Game/GameEventHandler.o"
	@echo "... Game/GameEventHandler.i"
	@echo "... Game/GameEventHandler.s"
	@echo "... Game/GarbageBlock.o"
	@echo "... Game/GarbageBlock.i"
	@echo "... Game/GarbageBlock.s"
	@echo "... Game/KeyboardController.o"
	@echo "... Game/KeyboardController.i"
	@echo "... Game/KeyboardController.s"
	@echo "... Game/VsGame.o"
	@echo "... Game/VsGame.i"
	@echo "... Game/VsGame.s"
	@echo "... InputManager.o"
	@echo "... InputManager.i"
	@echo "... InputManager.s"
	@echo "... Menus/KeyConfigMenu.o"
	@echo "... Menus/KeyConfigMenu.i"
	@echo "... Menus/KeyConfigMenu.s"
	@echo "... Menus/MainMenu.o"
	@echo "... Menus/MainMenu.i"
	@echo "... Menus/MainMenu.s"
	@echo "... Menus/Menu.o"
	@echo "... Menus/Menu.i"
	@echo "... Menus/Menu.s"
	@echo "... Menus/MenuItem.o"
	@echo "... Menus/MenuItem.i"
	@echo "... Menus/MenuItem.s"
	@echo "... Menus/OptionsMenu.o"
	@echo "... Menus/OptionsMenu.i"
	@echo "... Menus/OptionsMenu.s"
	@echo "... Menus/PauseMenu.o"
	@echo "... Menus/PauseMenu.i"
	@echo "... Menus/PauseMenu.s"
	@echo "... Rendering/BoardRenderer.o"
	@echo "... Rendering/BoardRenderer.i"
	@echo "... Rendering/BoardRenderer.s"
	@echo "... Rendering/ChainPopup.o"
	@echo "... Rendering/ChainPopup.i"
	@echo "... Rendering/ChainPopup.s"
	@echo "... Rendering/ComboPopup.o"
	@echo "... Rendering/ComboPopup.i"
	@echo "... Rendering/ComboPopup.s"
	@echo "... Rendering/EndlessGameRenderer.o"
	@echo "... Rendering/EndlessGameRenderer.i"
	@echo "... Rendering/EndlessGameRenderer.s"
	@echo "... Rendering/GameRenderer.o"
	@echo "... Rendering/GameRenderer.i"
	@echo "... Rendering/GameRenderer.s"
	@echo "... Rendering/GbQueueRenderer.o"
	@echo "... Rendering/GbQueueRenderer.i"
	@echo "... Rendering/GbQueueRenderer.s"
	@echo "... Rendering/Particle.o"
	@echo "... Rendering/Particle.i"
	@echo "... Rendering/Particle.s"
	@echo "... Rendering/Popup.o"
	@echo "... Rendering/Popup.i"
	@echo "... Rendering/Popup.s"
	@echo "... Rendering/Renderer.o"
	@echo "... Rendering/Renderer.i"
	@echo "... Rendering/Renderer.s"
	@echo "... Rendering/TitleScreenRenderer.o"
	@echo "... Rendering/TitleScreenRenderer.i"
	@echo "... Rendering/TitleScreenRenderer.s"
	@echo "... Rendering/VsGameRenderer.o"
	@echo "... Rendering/VsGameRenderer.i"
	@echo "... Rendering/VsGameRenderer.s"
	@echo "... SDLContext.o"
	@echo "... SDLContext.i"
	@echo "... SDLContext.s"
	@echo "... States/AIGameState.o"
	@echo "... States/AIGameState.i"
	@echo "... States/AIGameState.s"
	@echo "... States/DemoGameState.o"
	@echo "... States/DemoGameState.i"
	@echo "... States/DemoGameState.s"
	@echo "... States/EndlessGameState.o"
	@echo "... States/EndlessGameState.i"
	@echo "... States/EndlessGameState.s"
	@echo "... States/FadeTransition.o"
	@echo "... States/FadeTransition.i"
	@echo "... States/FadeTransition.s"
	@echo "... States/GameState.o"
	@echo "... States/GameState.i"
	@echo "... States/GameState.s"
	@echo "... States/OptionsMenuState.o"
	@echo "... States/OptionsMenuState.i"
	@echo "... States/OptionsMenuState.s"
	@echo "... States/State.o"
	@echo "... States/State.i"
	@echo "... States/State.s"
	@echo "... States/StateManager.o"
	@echo "... States/StateManager.i"
	@echo "... States/StateManager.s"
	@echo "... States/TitleScreen.o"
	@echo "... States/TitleScreen.i"
	@echo "... States/TitleScreen.s"
	@echo "... States/VsGameState.o"
	@echo "... States/VsGameState.i"
	@echo "... States/VsGameState.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

